/*
 *  UCF COP3330 Fall 2021 Assignment 4 Solutions
 *  Copyright 2021 Brian Reed
 */
@startuml

class Solution41 {
+main()
}

class NameSorter {
-arrayList<String> names

+readNames()
+outputNames()
}

Solution41 --o NameSorter
@enduml